import type { LocaleType } from '@/types/config'

const ZH_CN_CLASS_LABELS: Record<string, string> = {
  person: '人员',
  bicycle: '自行车',
  car: '汽车',
  motorcycle: '摩托车',
  motorbike: '摩托车',
  airplane: '飞机',
  aeroplane: '飞机',
  bus: '公交车',
  train: '火车',
  truck: '卡车',
  boat: '船',
  traffic_light: '交通信号灯',
  fire_hydrant: '消防栓',
  stop_sign: '停车标志',
  parking_meter: '停车计时器',
  bench: '长椅',
  bird: '鸟',
  cat: '猫',
  dog: '狗',
  horse: '马',
  sheep: '羊',
  cow: '牛',
  elephant: '大象',
  bear: '熊',
  zebra: '斑马',
  giraffe: '长颈鹿',
  backpack: '背包',
  umbrella: '雨伞',
  handbag: '手提包',
  tie: '领带',
  suitcase: '行李箱',
  frisbee: '飞盘',
  skis: '滑雪板',
  snowboard: '单板滑雪板',
  sports_ball: '球',
  kite: '风筝',
  baseball_bat: '棒球棒',
  baseball_glove: '棒球手套',
  skateboard: '滑板',
  surfboard: '冲浪板',
  tennis_racket: '网球拍',
  bottle: '瓶子',
  wine_glass: '酒杯',
  cup: '杯子',
  fork: '叉子',
  knife: '刀',
  spoon: '勺子',
  bowl: '碗',
  banana: '香蕉',
  apple: '苹果',
  sandwich: '三明治',
  orange: '橙子',
  broccoli: '西兰花',
  carrot: '胡萝卜',
  hot_dog: '热狗',
  pizza: '披萨',
  donut: '甜甜圈',
  doughnut: '甜甜圈',
  cake: '蛋糕',
  chair: '椅子',
  couch: '沙发',
  sofa: '沙发',
  potted_plant: '盆栽',
  bed: '床',
  dining_table: '餐桌',
  toilet: '马桶',
  tv: '电视',
  tvmonitor: '电视',
  laptop: '笔记本电脑',
  mouse: '鼠标',
  remote: '遥控器',
  keyboard: '键盘',
  cell_phone: '手机',
  mobile_phone: '手机',
  microwave: '微波炉',
  oven: '烤箱',
  toaster: '烤面包机',
  sink: '水槽',
  refrigerator: '冰箱',
  fridge: '冰箱',
  book: '书',
  clock: '时钟',
  vase: '花瓶',
  scissors: '剪刀',
  teddy_bear: '泰迪熊',
  hair_drier: '吹风机',
  hair_dryer: '吹风机',
  toothbrush: '牙刷',
  helmet: '安全帽',
  hardhat: '安全帽',
  hard_hat: '安全帽',
  safety_helmet: '安全帽',
  no_helmet: '未佩戴安全帽',
  without_helmet: '未佩戴安全帽',
  head: '头部',
  face: '人脸',
  smoke: '烟雾',
  smoking: '吸烟',
  cigarette: '香烟',
  fire: '火焰',
  flame: '火焰',
  fall: '跌倒',
  fallen_person: '跌倒人员',
  vehicle: '车辆',
  license_plate: '车牌',
  safety_vest: '反光背心',
  no_safety_vest: '未穿反光背心',
}

function normalizeClassLabel(label: string) {
  return label.trim().toLowerCase().replace(/[\s-]+/g, '_')
}

/**
 * 只改变检测类别的界面文本。类别 key/value 必须继续使用模型原值提交。
 */
export function localizeDetectionClassLabel(label: string, locale: LocaleType) {
  if (locale !== 'zh_CN')
    return label
  return ZH_CN_CLASS_LABELS[normalizeClassLabel(label)] ?? label
}
