const CLASS_LABEL_TRANSLATIONS: Record<string, string> = {
  person: '人员',
  bicycle: '自行车',
  car: '汽车',
  motorcycle: '摩托车',
  motorbike: '摩托车',
  airplane: '飞机',
  bus: '公交车',
  train: '火车',
  truck: '卡车',
  boat: '船',
  traffic_light: '交通灯',
  fire_hydrant: '消防栓',
  stop_sign: '停止标志',
  parking_meter: '停车计时器',
  bench: '长椅',
  bird: '鸟',
  cat: '猫',
  dog: '狗',
  horse: '马',
  sheep: '羊',
  cow: '牛',
  elephant: '大象',
  bear: '熊',
  zebra: '斑马',
  giraffe: '长颈鹿',
  backpack: '背包',
  umbrella: '雨伞',
  handbag: '手提包',
  tie: '领带',
  suitcase: '行李箱',
  frisbee: '飞盘',
  skis: '滑雪板',
  snowboard: '单板滑雪板',
  sports_ball: '球',
  kite: '风筝',
  baseball_bat: '棒球棒',
  baseball_glove: '棒球手套',
  skateboard: '滑板',
  surfboard: '冲浪板',
  tennis_racket: '网球拍',
  bottle: '瓶子',
  wine_glass: '酒杯',
  cup: '杯子',
  fork: '叉子',
  knife: '刀具',
  spoon: '勺子',
  bowl: '碗',
  banana: '香蕉',
  apple: '苹果',
  sandwich: '三明治',
  orange: '橙子',
  broccoli: '西兰花',
  carrot: '胡萝卜',
  hot_dog: '热狗',
  pizza: '披萨',
  donut: '甜甜圈',
  cake: '蛋糕',
  chair: '椅子',
  couch: '沙发',
  sofa: '沙发',
  potted_plant: '盆栽',
  bed: '床',
  dining_table: '餐桌',
  toilet: '马桶',
  tv: '电视',
  laptop: '笔记本电脑',
  mouse: '鼠标',
  remote: '遥控器',
  keyboard: '键盘',
  cell_phone: '手机',
  microwave: '微波炉',
  oven: '烤箱',
  toaster: '烤面包机',
  sink: '水槽',
  refrigerator: '冰箱',
  book: '书',
  clock: '时钟',
  vase: '花瓶',
  scissors: '剪刀',
  teddy_bear: '玩具熊',
  hair_drier: '吹风机',
  toothbrush: '牙刷',
  helmet: '安全帽',
  no_helmet: '未戴安全帽',
  head: '头部',
  vest: '反光背心',
  safety_vest: '反光背心',
  reflective_vest: '反光背心',
  smoke: '烟雾',
  dust: '粉尘',
  cigarette: '香烟',
  fire: '火焰',
  phone: '手机',
  mobile_phone: '手机',
  trash: '垃圾',
  garbage: '垃圾',
  trash_can: '垃圾桶',
  garbage_can: '垃圾桶',
  weapon: '武器',
};

export function isAsciiClassLabel(value?: string | null) {
  const text = String(value ?? '').trim();
  return !!text && /^[\x20-\x7E]+$/.test(text);
}

export function normalizeClassLabelKey(value?: string | null) {
  return String(value ?? '')
    .trim()
    .toLowerCase()
    .replace(/[\s-]+/g, '_');
}

export function translateClassLabel(value?: string | null) {
  const text = String(value ?? '').trim();
  if (!text)
    return '';
  return CLASS_LABEL_TRANSLATIONS[normalizeClassLabelKey(text)] ?? text;
}
